//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionEscritoroSOA.WCFServiceSOA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ventas", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceSOA")]
    [System.SerializableAttribute()]
    public partial class Ventas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadVendidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadVendida {
            get {
                return this.CantidadVendidaField;
            }
            set {
                if ((this.CantidadVendidaField.Equals(value) != true)) {
                    this.CantidadVendidaField = value;
                    this.RaisePropertyChanged("CantidadVendida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articulos", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceSOA")]
    [System.SerializableAttribute()]
    public partial class Articulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExistenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Existencias {
            get {
                return this.ExistenciasField;
            }
            set {
                if ((this.ExistenciasField.Equals(value) != true)) {
                    this.ExistenciasField = value;
                    this.RaisePropertyChanged("Existencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentasGlobales", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceSOA")]
    [System.SerializableAttribute()]
    public partial class VentasGlobales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadVendidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalVentasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadVendida {
            get {
                return this.CantidadVendidaField;
            }
            set {
                if ((this.CantidadVendidaField.Equals(value) != true)) {
                    this.CantidadVendidaField = value;
                    this.RaisePropertyChanged("CantidadVendida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalVentas {
            get {
                return this.TotalVentasField;
            }
            set {
                if ((this.TotalVentasField.Equals(value) != true)) {
                    this.TotalVentasField = value;
                    this.RaisePropertyChanged("TotalVentas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceSOA.IWCFServiceSOA")]
    public interface IWCFServiceSOA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceSOA/obtenerVentasporArticulo", ReplyAction="http://tempuri.org/IWCFServiceSOA/obtenerVentasporArticuloResponse")]
        EvaluacionEscritoroSOA.WCFServiceSOA.Ventas[] obtenerVentasporArticulo(string ventas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceSOA/obtenerVentasporArticulo", ReplyAction="http://tempuri.org/IWCFServiceSOA/obtenerVentasporArticuloResponse")]
        System.Threading.Tasks.Task<EvaluacionEscritoroSOA.WCFServiceSOA.Ventas[]> obtenerVentasporArticuloAsync(string ventas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceSOA/obtenerCantidadArticulos", ReplyAction="http://tempuri.org/IWCFServiceSOA/obtenerCantidadArticulosResponse")]
        EvaluacionEscritoroSOA.WCFServiceSOA.Articulos[] obtenerCantidadArticulos(string ventas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceSOA/obtenerCantidadArticulos", ReplyAction="http://tempuri.org/IWCFServiceSOA/obtenerCantidadArticulosResponse")]
        System.Threading.Tasks.Task<EvaluacionEscritoroSOA.WCFServiceSOA.Articulos[]> obtenerCantidadArticulosAsync(string ventas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceSOA/obtenerVentasGlobales", ReplyAction="http://tempuri.org/IWCFServiceSOA/obtenerVentasGlobalesResponse")]
        EvaluacionEscritoroSOA.WCFServiceSOA.VentasGlobales[] obtenerVentasGlobales(string ventas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceSOA/obtenerVentasGlobales", ReplyAction="http://tempuri.org/IWCFServiceSOA/obtenerVentasGlobalesResponse")]
        System.Threading.Tasks.Task<EvaluacionEscritoroSOA.WCFServiceSOA.VentasGlobales[]> obtenerVentasGlobalesAsync(string ventas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceSOAChannel : EvaluacionEscritoroSOA.WCFServiceSOA.IWCFServiceSOA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceSOAClient : System.ServiceModel.ClientBase<EvaluacionEscritoroSOA.WCFServiceSOA.IWCFServiceSOA>, EvaluacionEscritoroSOA.WCFServiceSOA.IWCFServiceSOA {
        
        public WCFServiceSOAClient() {
        }
        
        public WCFServiceSOAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceSOAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceSOAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceSOAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EvaluacionEscritoroSOA.WCFServiceSOA.Ventas[] obtenerVentasporArticulo(string ventas) {
            return base.Channel.obtenerVentasporArticulo(ventas);
        }
        
        public System.Threading.Tasks.Task<EvaluacionEscritoroSOA.WCFServiceSOA.Ventas[]> obtenerVentasporArticuloAsync(string ventas) {
            return base.Channel.obtenerVentasporArticuloAsync(ventas);
        }
        
        public EvaluacionEscritoroSOA.WCFServiceSOA.Articulos[] obtenerCantidadArticulos(string ventas) {
            return base.Channel.obtenerCantidadArticulos(ventas);
        }
        
        public System.Threading.Tasks.Task<EvaluacionEscritoroSOA.WCFServiceSOA.Articulos[]> obtenerCantidadArticulosAsync(string ventas) {
            return base.Channel.obtenerCantidadArticulosAsync(ventas);
        }
        
        public EvaluacionEscritoroSOA.WCFServiceSOA.VentasGlobales[] obtenerVentasGlobales(string ventas) {
            return base.Channel.obtenerVentasGlobales(ventas);
        }
        
        public System.Threading.Tasks.Task<EvaluacionEscritoroSOA.WCFServiceSOA.VentasGlobales[]> obtenerVentasGlobalesAsync(string ventas) {
            return base.Channel.obtenerVentasGlobalesAsync(ventas);
        }
    }
}
